<Window x:Class="DDrop.Utility.ExceptionHandling.Windows.ExceptionWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        Title="Непредвиденная ошибка приложения"
        Width="700"
        MaxHeight="650"
        Closed="OnExceptionWindowClosed"
        ResizeMode="NoResize"
        SizeToContent="Height"
        mc:Ignorable="d"
        Topmost="True">
    <Window.Resources>
        <Style x:Key="Label"
               TargetType="TextBlock">
            <Setter Property="FontWeight" Value="Bold" />
            <Setter Property="Margin" Value="0,8,0,4" />
        </Style>
        <Style x:Key="Content"
               TargetType="TextBlock">
            <Setter Property="Margin" Value="0,4,0,8" />
        </Style>
    </Window.Resources>
    <Grid>
        <Grid.RowDefinitions>
            <!--  Info  -->
            <RowDefinition Height="auto" />
            <!--  Exception details  -->
            <RowDefinition Height="*" />
            <!--  Button  -->
            <RowDefinition Height="auto" />
        </Grid.RowDefinitions>

        <!--  Info  -->
        <TextBlock Margin="16"
                   FontSize="14"
                   Text="Произошла непредвиденная ошибка. Состояние приложения может быть повреждено."
                   TextWrapping="Wrap" />

        <!--  Exception details  -->
        <Border Grid.Row="1"
                MaxHeight="450"
                Background="#EEEEEE">
            <Expander Margin="16,8,16,8"
                      Header="Детали исключения">

                <ScrollViewer HorizontalScrollBarVisibility="Auto"
                              VerticalScrollBarVisibility="Auto">
                    <StackPanel>
                        <!--  Exception Message  -->
                        <TextBlock Style="{StaticResource Label}"
                                   Text="Сообщение исключения" />
                        <TextBlock Grid.Column="1"
                                   Text="{Binding Exception.Message, Mode=OneWay, TargetNullValue=-}"
                                   TextWrapping="Wrap" />
                        <!--  Exception Type  -->
                        <TextBlock Style="{StaticResource Label}"
                                   Text="Тип исключения" />
                        <TextBlock Style="{StaticResource Content}"
                                   Text="{Binding ExceptionType, Mode=OneWay, TargetNullValue=-}" />
                        <!--  Callstack  -->
                        <TextBlock Style="{StaticResource Label}"
                                   Text="Стэк вызовов" />
                        <TextBlock Style="{StaticResource Content}"
                                   Text="{Binding Exception.StackTrace, Mode=OneWay, TargetNullValue=-}" />
                        <!--  Inner exception  -->
                        <TextBlock Style="{StaticResource Label}"
                                   Text="Внутреннее исключение" />
                        <TextBlock Style="{StaticResource Content}"
                                   Text="{Binding Exception.InnerException, Mode=OneWay, TargetNullValue=-}" />
                    </StackPanel>
                </ScrollViewer>
            </Expander>
        </Border>
        <!--  Close Button  -->
        <Button Grid.Row="2"
                Margin="16"
                Padding="8"
                HorizontalAlignment="Right"
                Click="OnExitAppClick"
                Content="Закрыть приложение" />
    </Grid>
</Window>